### ISSUE TITLE
Why is `fetch-depth: 0` needed?

### ISSUE THREAD

**Issue by chancancode** [chancancode/branch-rename#7]
I tried setting this up on another repo I have today, and the mirror action failed without `fetch-depth: 0` ([logs](https://github.com/chancancode/ember-concurrency-async/runs/788778347?check_suite_focus=true)). The Git error was:

```
Run git push origin HEAD:master HEAD:main
  git push origin HEAD:master HEAD:main
  shell: /bin/bash -e {0}
To https://github.com/chancancode/ember-concurrency-async
 ! [rejected]        HEAD -> master (fetch first)
error: failed to push some refs to 'https://github.com/chancancode/ember-concurrency-async'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Which is similar to what I had encountered in the past. I brought back `fetch-depth: 0` for now since it is better for it to be a bit slow than for others to run into the problem, but I do think we should investigate what's up and whether we can do something a bit more targeted (e.g. fetching a single commit from each branch?).

**Comment by chancancode** [comment]
cc @dscho

**Comment by dscho** [comment]
> Updates were rejected because the remote contains work that you do
> hint: not have locally.

Hmm. I guess that means that it is the _local_ side that performs the computation whether it is a fast-forward or not... At least that is my current interpretation of this.

So indeed, increasing the fetch depth would fix this. But it would introduce another problem: if you have a long history, then the clone will take a _long_ time, leaving a window for `master` and `main` to diverge. And if it is unlikely that massive amounts of commits are pushed (or merged) in one go, then increasing the fetch depth gently (e.g. to `100`) might strike a much better balance there.

**Comment by chancancode** [comment]
@dscho Got a tweet from @zofrex about their GH action: https://github.com/marketplace/actions/mirror-branch

It [uses the API to update the ref](https://github.com/zofrex/mirror-branch/blob/ea152f124954fa4eb26eea3fe0dbe313a3a08d94/index.js#L13), I think switching to that will solve both our problems and remove the need to have the special paragraph about big repos. Thoughts?

**Comment by dscho** [comment]
> @dscho Got a tweet from @zofrex about their GH action: https://github.com/marketplace/actions/mirror-branch
> 
> It [uses the API to update the ref](https://github.com/zofrex/mirror-branch/blob/ea152f124954fa4eb26eea3fe0dbe313a3a08d94/index.js#L13), I think switching to that will solve both our problems and remove the need to have the special paragraph about big repos. Thoughts?

Yes, I think that's a good idea.

To help with protected branches, that Action probably needs to be taught an option to accept a specific PAT; that should be easy enough to add.

**Comment by chancancode** [comment]
> To help with protected branches, that Action probably needs to be taught an option to accept a specific PAT; that should be easy enough to add.

Good point. I'll open an issue there.

**Comment by chancancode** [comment]
Ah, [it already does](https://github.com/zofrex/mirror-branch/blob/ea152f124954fa4eb26eea3fe0dbe313a3a08d94/action.yml#L8-L13), just not documented

**Comment by dscho** [comment]
Oh, now that I think of it: maybe there is a way to prevent direct pushes to `master` by branch protections?

What I mean is this:

- having a workflow that fails for PRs targeting `master`
- marking that workflow as required in `master`'s branch protection
- adding an exception for a specific GitHub account whose PAT is then used to mirror the default branch to `master` (this would require aforementioned option in that action)
- obviously, this PAT not only needs to be generated and added as a secret, but care needs to be exercised never to push manually as that user.

What do you think?

**Comment by chancancode** [comment]
@dscho I think turning on either "Require pull request reviews before merging" or "Require status checks to pass before merging" already forbids pushing to `master` directly (other than admins, if excluded).

In repos that uses branch protection, I think it's less about forbidding pushing to `master` directly (because it already doesn't work), it's more about giving contributors the signal that they need to change the local `master` branch to track the `main` remote branch (whether they rename it locally or not is up to them and doesn't really matter), because the `master` remote branch will soon disappear. (The deprecation workflow in the guide does fail the status check if a PR is targeting `master`.)

In repos that doesn't use those branch protection, it's actually good that people (who missed the memo) pushes to the master branch, because they will trigger the "deprecation" workflow and get an @-mention from the bot with the steps to migrate.

**Comment by dscho** [comment]
> @dscho I think turning on either "Require pull request reviews before merging" or "Require status checks to pass before merging" already forbids pushing to `master` directly (other than admins, if excluded).

Right, I meant the required status checks.

> In repos that uses branch protection, I think it's less about forbidding pushing to `master` directly (because it already doesn't work), it's more about giving contributors the signal that they need to change the local `master` branch to track the `main` remote branch (whether they rename it locally or not is up to them and doesn't really matter), because the `master` remote branch will soon disappear. (The deprecation workflow in the guide does fail the status check if a PR is targeting `master`.)
> 
> In repos that doesn't use those branch protection, it's actually good that people (who missed the memo) pushes to the master branch, because they will trigger the "deprecation" workflow and get an @-mention from the bot with the steps to migrate.

My thought was that preventing direct pushes would send an even stronger signal than @-mentions (which I, for one, sometimes miss for days).
